fs=yes
#geometry=50%:50%

volume=60

sub-pos=100
sub-font-size=30

vo=gpu-next
hwdec=vdpau
gpu-context=x11egl
keepaspect=yes

scale=bilinear
dscale=bilinear
dither=no
correct-downscaling=no
linear-downscaling=no
sigmoid-upscaling=no
hdr-compute-peak=no
allow-delayed-peak-detect=yes


# demuxer-readahead-secs=300
demuxer-max-bytes=50MiB
# demuxer-max-back-bytes=50MiB

# cache=yes
# cache-secs=300
# cache-pause=no
# stream-buffer-size=20MiB

# ao=alsa
# autosync=30

demuxer-cache-dir=/home/masud/.config/mpv/cache/
icc-cache-dir=/home/masud/.config/mpv/cache/
gpu-shader-cache-dir=/home/masud/.config/mpv/cache/
screenshot-directory=/home/masud/.config/mpv/cache/

watch-later-dir=/home/masud/.config/mpv/cache/

# 240p 
#ytdl-format="bestvideo[vcodec^=avc1][height=240]+bestaudio/best[vcodec^=avc1][height=480]/bestvideo[vcodec^=avc1][height=240]+bestaudio/best[vcodec^=avc1][height=480]/best"


# 360p
#ytdl-format="bestvideo[vcodec^=avc1][height=360]+bestaudio/best[vcodec^=avc1][height=480]/bestvideo[vcodec^=avc1][height=360]+bestaudio/best[vcodec^=avc1][height=480]/best"

# 480p
# ytdl-format="bestvideo[vcodec^=avc1][height=480]+bestaudio/best[vcodec^=avc1][height=480]/bestvideo[vcodec^=avc1][height=720]+bestaudio/best[vcodec^=avc1][height=480]/best"

# 720p
ytdl-format="bestvideo[vcodec^=avc1][height=720]+bestaudio/best[vcodec^=avc1][height=720]/bestvideo[vcodec^=avc1][height=720]+bestaudio/best[vcodec^=avc1][height=480]/best"

# 1080p
#ytdl-format="bestvideo[vcodec^=avc1][height=1080]+bestaudio/best[vcodec^=avc1][height=1080]/bestvideo[vcodec^=avc1][height=720]+bestaudio/best[vcodec^=avc1][height=480]/best"

[eye-cancer]
sharpen=5

[yt]
loop-file=inf
user-agent='Opera/9.80 (Android; Opera Mini/36.2.2254/119.132; U; id) Presto/2.12.423 Version/12.16)'

# [radio]
# cache=yes
# cache-pause=no
# cache-secs=5
# demuxer-readahead-secs=5
# demuxer-max-bytes=300K
# stream-buffer-size=300K


