zstyle :plugin:fast-syntax-highlighting theme "forest"
typeset -g FAST_THEME_NAME="forest"
: ${FAST_HIGHLIGHT_STYLES[forestdefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[forestunknown-token]:=fg=124,bold}
: ${FAST_HIGHLIGHT_STYLES[forestreserved-word]:=fg=186}
: ${FAST_HIGHLIGHT_STYLES[forestalias]:=fg=101}
: ${FAST_HIGHLIGHT_STYLES[forestsuffix-alias]:=fg=101}
: ${FAST_HIGHLIGHT_STYLES[forestbuiltin]:=fg=101}
: ${FAST_HIGHLIGHT_STYLES[forestfunction]:=fg=101}
: ${FAST_HIGHLIGHT_STYLES[forestcommand]:=fg=101}
: ${FAST_HIGHLIGHT_STYLES[forestprecommand]:=fg=101}
: ${FAST_HIGHLIGHT_STYLES[forestcommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[foresthashed-command]:=fg=101}
: ${FAST_HIGHLIGHT_STYLES[forestpath]:=fg=107}
: ${FAST_HIGHLIGHT_STYLES[forestpath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[forestglobbing]:=fg=114}
: ${FAST_HIGHLIGHT_STYLES[forestglobbing-ext]:=fg=118}
: ${FAST_HIGHLIGHT_STYLES[foresthistory-expansion]:=fg=114}
: ${FAST_HIGHLIGHT_STYLES[forestsingle-hyphen-option]:=fg=65}
: ${FAST_HIGHLIGHT_STYLES[forestdouble-hyphen-option]:=fg=65}
: ${FAST_HIGHLIGHT_STYLES[forestback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[forestsingle-quoted-argument]:=fg=186}
: ${FAST_HIGHLIGHT_STYLES[forestdouble-quoted-argument]:=fg=186}
: ${FAST_HIGHLIGHT_STYLES[forestdollar-quoted-argument]:=fg=186}
: ${FAST_HIGHLIGHT_STYLES[forestback-or-dollar-double-quoted-argument]:=fg=65}
: ${FAST_HIGHLIGHT_STYLES[forestback-dollar-quoted-argument]:=fg=65}
: ${FAST_HIGHLIGHT_STYLES[forestassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[forestredirection]:=none}
: ${FAST_HIGHLIGHT_STYLES[forestcomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[forestvariable]:=none}
: ${FAST_HIGHLIGHT_STYLES[forestmathvar]:=fg=114}
: ${FAST_HIGHLIGHT_STYLES[forestmathnum]:=fg=107}
: ${FAST_HIGHLIGHT_STYLES[forestmatherr]:=fg=124}
: ${FAST_HIGHLIGHT_STYLES[forestassign-array-bracket]:=fg=101}
: ${FAST_HIGHLIGHT_STYLES[forestfor-loop-variable]:=none}
: ${FAST_HIGHLIGHT_STYLES[forestfor-loop-number]:=fg=107}
: ${FAST_HIGHLIGHT_STYLES[forestfor-loop-operator]:=fg=186}
: ${FAST_HIGHLIGHT_STYLES[forestfor-loop-separator]:=fg=109}
: ${FAST_HIGHLIGHT_STYLES[forestexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[foresthere-string-tri]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[foresthere-string-text]:=underline}
: ${FAST_HIGHLIGHT_STYLES[foresthere-string-var]:=fg=65,underline}
: ${FAST_HIGHLIGHT_STYLES[forestsecondary]:=zdharma}
: ${FAST_HIGHLIGHT_STYLES[forestcase-input]:=fg=101}
: ${FAST_HIGHLIGHT_STYLES[forestcase-parentheses]:=fg=65}
: ${FAST_HIGHLIGHT_STYLES[forestcase-condition]:=underline}
: ${FAST_HIGHLIGHT_STYLES[forestcorrect-subtle]:=bg=55}
: ${FAST_HIGHLIGHT_STYLES[forestincorrect-subtle]:=bg=52}
: ${FAST_HIGHLIGHT_STYLES[forestsubtle-separator]:=none}
: ${FAST_HIGHLIGHT_STYLES[forestsubtle-bg]:=bg=18}
: ${FAST_HIGHLIGHT_STYLES[forestpath-to-dir]:=fg=107,underline}
: ${FAST_HIGHLIGHT_STYLES[forestpaired-bracket]:=bg=blue}
: ${FAST_HIGHLIGHT_STYLES[forestbracket-level-1]:=fg=green,bold}
: ${FAST_HIGHLIGHT_STYLES[forestbracket-level-2]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[forestbracket-level-3]:=fg=cyan,bold}
: ${FAST_HIGHLIGHT_STYLES[forestglobal-alias]:=bg=55}
: ${FAST_HIGHLIGHT_STYLES[forestsubcommand]:=fg=186}
: ${FAST_HIGHLIGHT_STYLES[forestsingle-sq-bracket]:=fg=101}
: ${FAST_HIGHLIGHT_STYLES[forestdouble-sq-bracket]:=fg=101}
: ${FAST_HIGHLIGHT_STYLES[forestdouble-paren]:=fg=186}
: ${FAST_HIGHLIGHT_STYLES[forestoptarg-string]:=fg=186}
: ${FAST_HIGHLIGHT_STYLES[forestoptarg-number]:=fg=107}
: ${FAST_HIGHLIGHT_STYLES[forestrecursive-base]:=fg=183}
