#!/bin/sh

# vim to nvim
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# EDITOR
alias \
 v="$EDITOR" \
 q="exit" \

# tmux
alias \
 t="tmux" \
 ta0="tmux attach-session -t 0" \
 ta="tmux attach-session -t" \
 tl="tmux ls" \

# Files

# List
alias \
 ls="ls --color=auto --group-directories-first" \
 lah="exa -la --group-directories-first" \

# Operation
alias \
 ..="cd .." \
 cp="cp -v" \
 mv="mv -v" \
 rm="rm -v" \
 rmd="rmdir -v" \
 mkd="mkdir -pv" \

# Navigation
alias \
 dcc="cd /home/masud/.cache" \
 dcf="cd /home/masud/.config" \
 dcfs="cd /home/masud/.config/shellrc" \
 dcfz="cd /home/masud/.config/zsh" \
 dcw="cd /home/masud/.config/vimwiki" \
 dck="cd /home/masud/.config/vimwiki/keep" \
 dls="cd /home/masud/.local/share" \
 dlb="cd /home/masud/.local/bin" \
 dlbs="cd /home/masud/.local/bin/scripts" \
 dh="cd /home/masud" \
 ddl="cd /home/masud/Downloads" \
 dn="cd /home/masud/Documents" \
 dp="cd /home/masud/Pictures" \
 dm="cd /home/masud/Music" \
 dv="cd /home/masud/Videos" \
 dw="cd /home/masud/Desktop" \
 dda="cd /home/masud/Downloads/AUR" \
 dg="cd /home/masud/Downloads/Git" \
 dga="cd /home/masud/Downloads/Git/arch" \
 dgd="cd /home/masud/Downloads/Git/dwm" \
 dgb="cd /home/masud/Downloads/Git/dwmblocks" \
 dgs="cd /home/masud/Downloads/Git/st" \
 fv="$EDITOR /home/masud/.config/nvim/init.vim" \
 fz="$EDITOR /home/masud/.config/zsh/.zshrc" \
 fa="$EDITOR /home/masud/.config/shellrc/aliasrc" \
 fzfn="$EDITOR /home/masud/.config/shellrc/zshfnrc" \
 fzp="$EDITOR /home/masud/.profile" \

# fzf
alias \
 e="fzf_file" \
 f="fzf_cd" \
 k="fzf_kill" \
 h="fzf_history" \

# Database
alias \
 updb="sudo updatedb" \

# Info
alias \
 pdw="pwd" \
 free="free -mt" \
 diff="diff --color=auto" \
 df="df -h" \

# Userlist
alias \
 userlist="cut -d: -f1 /etc/passwd" \

# HARDWARE
alias \
 hw="hwinfo --short" \

# Grep
alias \
 grep="grep --color=auto" \
 egrep="egrep --color=auto" \
 fgrep="fgrep --color=auto" \

# Merge
# alias \
# merge="xrdb -merge ~/.Xresources" \

# Conky
# alias \
# kc="killall conky" \

# MICROCODE
# alias \
# microcode="grep . /sys/devices/system/cpu/vulnerabilities/*" \

# GRUB
alias \
 update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \

# FONTS
alias \
 fc="sudo fc-cache -fv" \

# init
alias \
 sys="sudo sv" \
# sys="sudo systemctl"

# MIRROR
alias \
 mirror="sudo reflector -p https,http,ftp -f 5 -l 5 --verbose --save /etc/pacman.d/mirrorlist-arch" \
 mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist-arch" \
 mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist-arch" \
 mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist-arch" \
 mirrorb="sudo reflector -f 10 --country Bangladesh --save /etc/pacman.d/mirrorlist-arch" \

# PACMAN
alias \
 update="sudo pacman --color auto -Syyu" \
 up="sudo pacman --color auto -Syu" \
 upig="sudo pacman --color auto -Syu --ignore" \
 pacs="pacman --color auto -Ss" \
 inp="sudo pacman --color auto -S" \
 linp="sudo pacman --color auto -U" \
 rmv="sudo pacman --color auto -Rns" \

alias \
 unlock="sudo rm /var/lib/pacman/db.lck" \
 armv="sudo pacman -Rns $(pacman -Qtdq)" \
 cc="sudo pacman -Sc" \
 nrp="pacman -Qdt" \
 lfp="pacman -Qqm" \
 fp="pacman -Qm" \
 efp="pacman -Qqe" \

alias \
 rip="expac --timefmt='%Y-%m-%d %T' '%l\t%n %v' | sort | tail -100" \

# AUR
alias \
 inpkg="makepkg -si" \

# trizen
alias \
 tzn="trizen" \
 tinp="trizen -S" \
 tpacs="trizen -Ss" \
 tznc="trizen -G" \
 uptzn="trizen -Syu --noconfirm" \
 tznskip="trizen -S --skipinteg" \

# yay
# alias \
# yinp="yay -S" \
# yayskip="yay -S --mflags --skipinteg" \
# upyay="yay -Syu --noconfirm" \

# c source
alias \
    cinp="sudo make install" \
    crmv="sudo make uninstall" \

# network wpa_supplicant; nmtui
alias \
    nmc="nmtui connect"
# wpa="sudo wpa_supplicant -B -i wlp4s0 -c /etc/wpa_supplicant/wpa_supplicant-wlp4s0.conf && sudo dhcpcd wlp4s0" \

# MOUNT
alias \
 mount="udisksctl mount -b" \
 usb="udisksctl mount -b /dev/sdb1" \
 uusb="udisksctl unmount -b /dev/sdb1" \
 eusb="udisksctl power-off -b /dev/sdb1" \
 sdx="mountjutsu" \

# MAIL
alias \
 ibx="neomutt" \
 mail="mw -Y; neomutt" \
 mp="mw -y mparvz@gmail.com; neomutt" \
 ib="mw -y imrufbd@gmail.com; neomutt" \
 rry="mw -y riponridwan@yahoo.com; neomutt" \
 lic="mw -y riprid@cock.li; neomutt" \

# TRANSMISSION
alias \
 pfx="peerflix -k -f /home/masud/Videos/ptfx" \
 tfx="torrentflix" \


# Calculator
alias \
 math="mathomatic" \
 pc="python -ic 'from __future__ import division; from math import *; from random import *'" \
 c2='units' \
 sm="sc-im" \

# Misc. App
alias \
 snv="sudo nvim" \
 m="cmus" \
 vol="pulsemixer" \
 def="sdcv" \
 rt="tuir" \
 keep="keepcli" \
 pdf="zathura" \
 img="sxiv" \
 el="elinks" \
 ka="killall" \
 weather="curl wttr.in/khagrachari" \
 xp="xclip -o" \
 uc="ucollage" \
 sw="termdown" \
 abook="abook --config "$XDG_CONFIG_HOME"/abook/abookrc --datafile "$XDG_DATA_HOME"/abook/addressbook" \

# books="pysheng" \
# drive="gdrive" \
# imgur="imgur_downloader" \
# e.g="tldr" \

# ibus="ibus-daemon -xdr" \
# music="ncmpcpp" \
# vim="nvim" \

# GIT
alias \
 gitc="git clone" \
 gitu="git push -u origin master" \
 gitca="git commit -a" \
 gita="git add" \
 gits="git status" \

# ARCHIVE
alias \
 uz="atool -x" \
 z="atool -a" \

# arch-wiki-lite
alias \
 aw="wiki-search"

# tor/vpn
alias \
    v1="sudo openvpn --config ~/Downloads/openvpn/jp-free-01.protonvpn.com.udp.ovpn --mute 5 --mute-replay-warnings" \
    v2="sudo openvpn --config ~/Downloads/openvpn/jp-free-02.protonvpn.com.udp.ovpn --mute 5 --mute-replay-warnings" \
    v3="sudo openvpn --config ~/Downloads/openvpn/jp-free-03.protonvpn.com.udp.ovpn --mute 5 --mute-replay-warnings" \

# torsocks
# tor="sys start tor.service" \
# tors="sys stop tor.service" \
# ctorc="torsocks elinks "https://check.torproject.org/"" \
# ctorb="torsocks surf https://check.torproject.org/" \

#IP/PING
alias \
 pn="ping -c 3 google.com" \
 myip="ip addr show" \
 isp="curl ifconfig.co" \
 nsp="speedtest" \
 nsps="speedtest --simple --single" \
 ntm="speedometer -r wlp4s0 -t wlp4s0" \

#curl ifconfig.co/json
#http -b ifconfig.co
#wget -qO- ifconfig.co
#fetch -qo- https://ifconfig.co
#bat -print=b ifconfig.co/ip
#curl ifconfig.co/country
#curl ifconfig.co/country-iso
#curl ifconfig.co/city
#curl ifconfig.co/asn

#Firewall
alias \
 fwe="sudo ufw enable" \
 fwd="sudo ufw disable" \
 fws="sudo ufw status" \

#SSH/FTP
alias \
 sfu="sudo sv start sshd" \
 sfd="sudo sv stop sshd" \
 ftpu="sudo sv start vsftpd" \
 ftpd="sudo sv stop vsftpd" \
# termux="ssh -p 8022 u0_a127@192.168.137.234" \

# downloader
alias \
 wget="wget -c" \
 a2="aria2c" \
 a2p="aria2p" \
 a2s="a2pd start" \
 a2d="a2pd stop" \
 ttsm="tremc" \

# youtube-dl
alias \
 ytd-aac="youtube-dl --extract-audio --audio-format aac" \
 ytd-best="youtube-dl --extract-audio --audio-format best" \
 ytd-flac="youtube-dl --extract-audio --audio-format flac" \
 ytd-m4a="youtube-dl --extract-audio --audio-format m4a" \
 ytd-mp3="youtube-dl --extract-audio --audio-format mp3" \
 ytd-opus="youtube-dl --extract-audio --audio-format opus" \
 ytd-vorbis="youtube-dl --extract-audio --audio-format vorbis" \
 ytd-wav="youtube-dl --extract-audio --audio-format wav" \
 ytd-best="youtube-dl -f bestvideo+bestaudio " \
 ytd="youtube-dl" \
 ytdF="youtube-dl -F" \
 ytdf="youtube-dl -f" \
 ytv="youtube-viewer -C" \

#simple-mtpfs
#alias \
# phn="simple-mtpfs -l" \
# mphn="simple-mtpfs --device" 


#PNGLatex
#pnglatex -h for help
alias \
 eq="pnglatex -b Transparent -p amssymb:amsmath -d 300 -s 12 -o eq.png" \

# JavaWM
# alias \
# jwc="wmname LG3D"

# DE/WM
alias \
 gui="startx" \
# dwm="cp ~/.config/.xinit/dwm.xinitrc ~/.xinitrc && gui" \

# Corona
alias \
 covid="curl https://corona-stats.online\?source\=2" \
 covidbd="curl https://corona-stats.online/BD"

# POWERMANAGEMENT
# iph="i3exit suspend" \
# ipl="i3exit lock"    \
# ips="i3exit shutdown" \
# ipr="i3exit reboot"  \
# bat="cat /sys/class/power_supply/BAT?/capacity" \ 

# FETCH
alias \
 inf="pfetch" \
