#!/bin/sh

#fzf file, cd, history,  kill

fzf_file() 
        { 
        zle -I; FILE=$(find -type f 2> /dev/null | fzf +m) && vim "$FILE" ; 
#        zle -I; FILE=$(find -type f -not \( -path "./path1/*" -o -path "./path2/*" \)  2> /dev/null | fzf +m) && vim "$FILE" ; 
        }; 
    zle -N fzf_file;

fzf_cd() 
        { 
            zle -I; DIR=$(find ~/ -type d 2> /dev/null | fzf +m) && cd "$DIR" ; 
        }; 
    zle -N fzf_cd;

fzf_history() 
        { 
            zle -I; eval $(history | fzf -e +i +s | sed 's/ *[0-9]* *//') ; 
        }; 
    zle -N fzf_history;

fzf_kill() 
        { 
            zle -I; ps -ef | sed 1d | fzf -m | awk '{print $2}' | xargs kill -${1:-9} ; 
        }; 
    zle -N fzf_kill;

fssr() {
         case "$(printf "elvi\\nbms" | fzf -e)" in
            elvi) surfraw $(sr -elvi | awk -F'-' '{print $1}' | sed '/:/d' | awk '{$1=$1};1' | dmenu -l 5 -i -p "sr:>_") ;;
            bms) surfraw "$(cat ~/.config/surfraw/bookmarks | sed '/^$/d' | sort -n | fzf)" ;;
        esac 
       };
     zle -N fssr;

# nnn quitcd

n ()
    {
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
    }
