#!/bin/bash
# switch power state using dmenu(1)

#selection=$(printf 'lock\nlock-suspend\npoweroff\nreboot\nsuspend' \
#		| dmenu -f -i -l 5 -p Action: \
#			-fn monospace:size=12)

selection=$(printf 'lock\nsuspend\nshutdown\nreboot' \
		| dmenu  -i -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'Hack:bold:pixelsize=16' -p ">>>" \
)

case "${selection}" in
	lock)
		i3exit ${selection}
		;;
	shutdown|reboot|suspend)
		i3exit ${selection}
		;;
esac
