#!/usr/bin/env sh

# In LARBS, ~/.config/wall.png is the location of the system wallpaper.  This
# script, if given an argument, moves it there.  This script without an
# argument sets ~/.config/wall.png as the wallpaper, which is required on login
# if you don't want a blakc screen.

[ ! -z "$1" ] && cp "$1" ~/Pictures/feh/wm/wall.png && notify-send -i "$HOME/Pictures/feh/wm/wall.png" "Wallpaper changed."
xwallpaper --zoom ~/Pictures/feh/wm/wall.png
